name: cmad
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.20
  - matplotlib
  - scipy>=1.1.0
  - jupyter
  - pytest
  - coverage>=6.4
  - pytest-cov
  - pip
  - setuptools
  - scikit-learn
  - sympy
  # documentation
  - sphinx
  - sphinx-gallery
  - pip:
    - sphinx_copybutton
    - sphinx_rtd_theme
    - numpydoc
    - sphinx_automodapi
    - jax[cpu]
